general:
  data_path: "./data/"
  model_name: "digit82/kobart-summarization"
  output_dir: "./checkpoints/"

tokenizer:
  encoder_max_len: 512
  decoder_max_len: 100
  bos_token: "<s>"
  eos_token: "</s>"
  special_tokens:
    - "#Person1#"
    - "#Person2#"
    - "#Person3#"
    - "#PhoneNumber#"
    - "#Address#"
    - "#PassportNumber#"

training:
  num_train_epochs: 8
  learning_rate: 1e-5
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  warmup_ratio: 0.1
  weight_decay: 0.01
  generation_max_length: 100

inference:
  ckt_path: "./checkpoints/best_model"
  result_path: "./prediction/"
  generate_max_length: 100
  batch_size: 16
  no_repeat_ngram_size: 2
  early_stopping: true
  remove_tokens:
    - "<usr>"
    - "<s>"
    - "</s>"
    - "<pad>"
